### PR TITLE
fix: move feedbackWidget to footer

### LINKED ISSUE #584: Feedbackwidget overlaps content
**Describe the bug**
Feedback Widget is overlapping main content 

**Screenshot**
Screenshot 2024-05-29 at 16 23 54

**Expected behaviour**
Feedback Widget is located in footer 

- [ ] update `MIGRATION.md`
- [ ] update docs

### PR DESCRIPTION
**Pull request by PhilKsr**
## DESCRIPTION

FeedbackWidget is moved to footer as child

### TO-DO

- [x] ~implement and update tests~
- [x] ~update docs~
- [x] pull `main` & resolve merge conflicts
- [x] check Vercel deployment

### CLOSES

closes #584

### CODE REVIEW

**Review by qhantom — COMMENTED** [review]
Nice! I thought about decreasing the size of the icon button a bit to have more vertical space to the top and bottom. What do you think? Just a bit maybe 🤔

File: packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx [hunk 1]
```diff
@@ -226,14 +226,11 @@ export function FeedbackWidget({
         size="xl"
```
Comment (qhantom) [inline packages/lib/src/components/FeedbackWidget/FeedbackWidget.tsx:226]: @PhilKsr I mean the overall action icon 🙂

File: packages/lib/src/components/Footer/Footer.module.css [hunk 2]
```diff
@@ -17,15 +17,14 @@
...
  */
 
-.footer__app-shell {
-  padding: var(--mantine-spacing-md);
-}
+
 
 .footer__flex {
-  margin-left: var(--mantine-spacing-xs);
+  padding: 0 var(--mantine-spacing-xs);
```
Comment (qhantom) [inline packages/lib/src/components/Footer/Footer.module.css:23]: My last annotation, I tried it with more horizontal padding and it looks a bit spacier 🙂 

```suggestion
  padding: 0 var(--mantine-spacing-xl);
```

**Review by qhantom — APPROVED** [review]
