### PR TITLE
fix: show buttons depending on rights on home page

### LINKED ISSUE #668: show buttons depend on rights on home page
**Describe the bug**
When a user does not have the corresponding rights to see users, the button on the home page should not be visualised.

**Expected behaviour**
No button is rendered if the user does not have the user read right.

**Screenshots**
image

- [ ] update `MIGRATION.md`
- [ ] update docs

### PR DESCRIPTION
**Pull request by CathrinTruchan**
## DESCRIPTION

The following was implemented in this PR: 
The `USER_READ` right is checked on the `HomeView` in order to render the button for the `UserView`.

### TO-DO

- [x] update MIGRATON.md
- [X] pull `main` & resolve merge conflicts
- [x] check Vercel deployment

### CLOSES

closes #668

### CODE REVIEW

File: packages/lib/src/components/Home/Home.tsx [hunk 1]
```diff
@@ -28,9 +28,13 @@ import classes from './Home.module.css'
 
 type Props = {
   onClickButton: (path: string) => void
+  showUserButtonRight?: boolean
```
Comment (qhantom) [inline packages/lib/src/components/Home/Home.tsx:31]: I'd prefer setting `showUserButtonRight` not to be optional but mandatory. And I'd change the name to `showUsersPageButton`. What do you think about both suggestions?

**Review by qhantom — CHANGES_REQUESTED** [review]

File: packages/lib/src/components/Home/Home.tsx (hunk 1 above)
Comment (CathrinTruchan) [reply packages/lib/src/components/Home/Home.tsx]: Totally agree with you. I changed both.

**Review by qhantom — APPROVED** [review]
Fire 🔥
