### PR TITLE
navbar pin icon problems

### LINKED ISSUE #770: NavBar Pin Problems
**Describe the bug**

1. Pinning and unpinning leads to the Pin icon disappearing in firefox and flickering in chrome
2. Pinning and unpinning leads to child nav items to disappear in firefox and flickering in chrome
3. When the color scheme is auto and the user prefers a dark theme, the Pin icon disappears
4. The pin icon appears in the mobile view, where it has no effect

**To Reproduce**

1. Go to any view
2. Click on pin icon twice
3. See error

- [ ] update `MIGRATION.md`
- [ ] update docs

### PR DESCRIPTION
**Pull request by f4-lex**
### CLOSES

closes #770

### CODE REVIEW

File: packages/app/src/components/layouts/AuthLayout.tsx [hunk 1]
```diff
@@ -286,16 +286,6 @@ export function AuthLayout({ children, ...props }: Props): JSX.Element | null {
...
-  useEffect(() => {
-    if (!isFixedNav) {
-      if (!isNotMobile) {
-        setIsFoldedNav(false)
-      } else {
-        setIsFoldedNav(true)
-      }
-    }
-  }, [isFixedNav, isNotMobile])
-
```
Comment (f4-lex) [inline packages/app/src/components/layouts/AuthLayout.tsx:298]: I don't really know what this effect was doing in the first place. When unsetting isFixedNav the cursor is usually on the Nav and isFoldedNav should be false and not set to true 🤷🏻‍♂️

Comment (PhilKsr) [reply packages/app/src/components/layouts/AuthLayout.tsx:298]: I think it was for issues with the submenu being partially displayed but it works without the code as well.

**Review by PhilKsr — CHANGES_REQUESTED** [review]
Looks good so far without a bunch of code. 
I only noticed, that submenus are not accessible in mobile anymore:
Screenshot 2025-04-14 at 14 18 12

**Review by PhilKsr — APPROVED** [review]
