### PR TITLE
fix: fix layout flickering by using mantine ssr package

### LINKED ISSUE #365: Fix layout flickering on initial load
**Describe the bug**
When loading Essencium, there is a short flickering of non-styled HTML.

**To Reproduce**
1. Go to [ https://staging.essencium.dev](https://staging.essencium.dev)
2. See flickering

**Expected behavior**
HTML is shown with its CSS.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by qhantom**
**DESCRIPTION**
 
This PR fixes the layout flickering on initial page load by utilising the `@mantine/next` and  package. Additionally, the `_documents.ts` file has been modified. It now takes the initial props on the server to render the HTML with the CSS inside (image is from the response of the HTML document):

image
 
**CLOSES**
 
Closes #365

### CODE REVIEW

File: packages/app/src/pages/_document.tsx [hunk 1]
```diff
@@ -17,21 +17,27 @@
...
 
-export default function Document(): JSX.Element {
-  return (
-    <Html lang="en">
-      <Head>
-        <link rel="icon" href="/img/web/favicon.ico" sizes="any" />
-        <link rel="apple-touch-icon" href="/img/web/apple-touch-icon.png" />
-      </Head>
+const getInitialProps = createGetInitialProps()
+// eslint-disable-next-line @typescript-eslint/naming-convention
```
Comment (PhilKsr) [inline packages/app/src/pages/_document.tsx:24]: Would you add a blank space sir? Thank you! 🎩

**Review by PhilKsr — CHANGES_REQUESTED** [review]
Exactly like mentioned in the docs, works fine 👌🏼

File: packages/app/src/pages/_document.tsx (hunk 1 above)
Comment (qhantom) [reply packages/app/src/pages/_document.tsx:24]: Sure thing!

**Review by PhilKsr — APPROVED** [review]
